### ISSUE TITLE
Grading - Scanning, Parsing

### ISSUE THREAD

**Issue by CharlesAverill** [graysoncroom/GCP#1]
# Grading - Scanning, Parsing

## Criteria

- [x] Compiles
- [x] Executes
- [x] Implements scanning
- [x] Implements parsing
- [x] Supports examples shown in class

## Notes

- Please add build/dependency instructions to your README
- Nitpick: consider switching to CMake for better portability
- It's going to be hard to extend `Token` the more lines like [these](https://github.com/graysoncroom/GCP/blob/0513065d5ec22fe06498749338cd5c4d994fd099/src/scanning/token.h#L43) you have, the C language has ~70 tokens. Not sure what the course of action here is but I think using templates has made this problem much more complicated than it is

## Course of Action

Unfinished - <b>complete before next deadline</b>
Please respond to this issue when the missing criteria above have been fulfilled, include the commit hash for the latest working commit

**Comment by graysoncroom** [comment]
cded4243ba2ae5e47e51ac26108ebcade2b8187c

**Summary**

Parsing is working with examples from class, however, there isn't a defined order of operations.
Also, expressions are evaluated from right-to-left.
I haven't decided if I want to leave it this way by default or change the evaluation to left-to-right.
For now I will keep it this way.

**Questions**

- What specifically are you looking for w.r.t. additional build/dependency instructions in the README?

  I listed the library that needs to be installed on the system trying to build this compiler, what needs to be updated in the Makefile, and the command (i.e. `make`) that is needed to execute the full clean + build.
  Happy to add more I just don't understand what more there is to add.

- Are we supposed to have support for "forced operation order" (e.g. parenthesis in C) by this point?

**Comment by graysoncroom** [comment]
**Other Notes**

I know the code is a little messy right now, but it works.
As time permits I'll clean it up more, reabstract, etc...

I'm actually not happy with the token abstraction again, but I plan on keeping it as is until I finish implementing transpilation to LLVM-IR.

Finally, ignore the failed build from github actions for now. I need to set up an optional make argument that specifies the system path to boost so that this works. I am also considering just removing boost as the latest version of the token abstraction doesn't require ithe bimap implementation from this library.
utils/arguments.cpp uses boost program options but I shouldn't need to require boost just to parse args...

**Parsing**

Right now parsing is implemented using recursion. You mentioned earlier today that there was some method of parsing trees in particular that you wanted us to use? Maybe?

Regardless, I wasn't there for that lecture so I tried a few things and landed on a naive recursive assignment of terminal expressions to left child nodes. 
I imagine changing parsing to favor left expressions before right is as easy as assigning terminal expressions to right child nodes instead of left, but I haven't yet tried.
