### ISSUE TITLE
LLVM, Print Statements

### ISSUE THREAD

**Issue by CharlesAverill** [graysoncroom/GCP#2]
# Grading - LLVM, Print Statements

## Criteria

- [x] Compiles
- [x] Executes
- [x] Implements features shown in class
- [x] Supports examples shown in class

## Notes

LLVM is a-ok 

Seems like you have a bug in your precedence logic: 
`2 + 3 * 5 - 8 / 3` evaluates to `11`, but it should evaluate to `15` if we're following standard precedence rules. I checked this on commit `af466815abc016da136189339a4e31b3f4f48d5f` which seems to be when you finished the print statements assignment. Also, if this is a feature and not a bug just let me know the reason, no rule against different precedences.

## Course of Action

Unfinished - <b>complete before next deadline</b>
Please respond to this issue when the missing criteria above have been fulfilled, include the commit hash for the latest working commit

**Comment by graysoncroom** [comment]
> Seems like you have a bug in your precedence logic:
2 + 3 * 5 - 8 / 3 evaluates to 11, but it should evaluate to 15 if we're following standard precedence rules.
> if this is a feature and not a bug just let me know the reason

This is less of a "feature" per se and more of an "I don't know what direction I'm taking this language in yet" sort of thing.

I like the idea of always requiring parenthesis to explicitly state eval order and then providing some sort of syntactic sugar for making this less ugly.

I may implement precedence rules at some point once the language takes shape a little more, but as of right now, the strict right-to-left precedence is intentional.

This decision was mentioned in my reply to the previous issue. 
See [Grading - Scanning, Parsing](https://github.com/graysoncroom/GCP/issues/1)
